name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Replace plugin code
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.DEV_DEPLOY_KEY }}
      with:
        options: '--exclude=.git'
        src: '.'
        dest: 'root@68.183.243.27:/var/www/moodle/question/type/coderunner/'
